name: 0hrdesign
favicon: null
layout_spectrum: 0.5076510396320373
typography_spectrum: 0.39082660246640444
title: Zero Hour Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dddddd'
    - '#989898'
    - '#0a0000'
    - '#b00000'
    - '#c95729'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.7812500756699592
purpose: []
