typography_spectrum: 0.07012
color:
  brandColors:
    - '#dddddd'
    - '#989898'
    - '#0a0000'
    - '#b00000'
    - '#c95729'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.7812500756699592
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ross Lee
  email: zero@0hrdesign.com
  url: 0hrdesign.com
name: 0hrdesign
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Zero Hour Design
purpose: []
