name: 0hrdesign
favicon: null
layout_spectrum: 0.5076510396320373
typography_spectrum: 0.39082660246640444
title: Zero Hour Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a3719'
    - '#ffffff'
    - '#9d8c68'
    - '#110300'
    - '#c0bb98'
  brandStrength: 0.5
  lightness: 0.19700149120762944
  saturation: 0.7991024821531028
  rhythmicContrast: 0.7812500756699592
purpose: []
