typography_spectrum: 0.32965223700739443
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.7589208681602031
  lightness: 0.2584206291940063
  saturation: 0.2976837868336588
  rhythmicContrast: 0.3084950731135905
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5582032438833266
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ross Lee
  email: zero@0hrdesign.com
  url: 0hrdesign.com
name: 0hrdesign
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Zero Hour Design
purpose: []
